Repository systers/sysbot, pull requests merged in 2018-08, with the labels that each got.

#134 feat: Added feature to mock event delivery. Fixes #132
  simulate/simulate.py
Labels: Approved, GSoC-18, enhancement

#138 feat: Feature to add multiple labels using single command with comma seperated label names
  code/github_functions.py
  code/main_server.py
  tests/test_github_functions.py
  tests/test_main_server.py
Labels: GSoC-18, enhancement, not reviewed

#135 fix: Fixed overlapping language case
  code/slack_functions.py
Labels: Approved

#140 feat: Added feature to automatically change PR labels based on reviews
  code/github_functions.py
  code/main_server.py
  tests/setup_data.py
  tests/test_github_functions.py
Labels: GSoC-18, Priority: HIGH, not reviewed

#142 feat: Added feature to view issue content on Slack
  code/github_functions.py
  code/main_server.py
  code/messages.py
  code/slack_functions.py
  tests/setup_data.py
  tests/test_github_functions.py
  tests/test_slack_functions.py
Labels: GSoC-18, Priority: HIGH, not reviewed

#146 chore: Added encrypted keys and ways to extract them
  decoder.py
  docs/exporting_keys.md
  generate_tokens.sh
Labels: GSoC-18, not reviewed

#150 documentation: Updated documentation
  code/dictionaries.py
  code/main_server.py
  code/messages.py
  docs/README.md
  requirements.txt
Labels: GSoC-18, documentation, not reviewed

#151 feat: Added feature to label issues from Slack. Added tests
  PULL_REQUEST_TEMPLATE.md
  code/github_functions.py
  code/main_server.py
  code/messages.py
  code/slack_functions.py
  docs/README.md
  tests/setup_data.py
  tests/test_main_server.py
  tests/test_slack_functions.py
Labels: GSoC-18, enhancement, not reviewed

#158 fix: Added minor fixes to pass tests and change PR template
  .coveragerc
  code/github_functions.py
  code/main_server.py
  code/slack_functions.py
  code/topic_extractor.py
  deploy.sh
  docs/template_matching_design.md
  simulate/data/github_data.json
  simulate/simulate.py
  tests/setup_data.py
  tests/test_github_functions.py
  tests/test_main_server.py
  tests/test_slack_functions.py
Labels: not reviewed

#160 fix: Fixing auto-deployment
  code/topic_extractor.py
  deploy.sh
  run.py
Labels: not reviewed

#162 fix: Minor change in testing.sh to download nltk data before running tests
  testing.sh
Labels: not reviewed

#164 Gsoc 18 work
  .coveragerc
  .elasticbeanstalk/config.yml
  .gitignore
  .travis.yml
  PULL_REQUEST_TEMPLATE.md
  README.md
  code/__init__.py
  code/auth_credentials.py
  code/dictionaries.py
  code/dictionaries_test.py
  code/github_functions.py
  code/main_server.py
  code/messages.py
  code/request_urls.py
  code/slack_functions.py
  code/topic_extractor.py
  decoder.py
  deploy.sh
  docs/CONTRIBUTING.md
  docs/README.md
  docs/answering_design.md
  docs/code_of_conduct.md
  docs/exporting_keys.md
  docs/help_links.txt
  docs/help_phrases.txt
  docs/nlp_explainations.md
  docs/reporting_guidelines.md
  docs/template_matching_design.md
  generate_tokens.sh
  requirements.txt
  run.py
  setup.cfg
  simulate/data/github_data.json
  simulate/data/slack_data.json
  simulate/simulate.py
  testing.sh
  tests/__init__.py
  tests/setup_data.py
  tests/test_github_functions.py
  tests/test_main_server.py
  tests/test_slack_functions.py
Labels: not reviewed

#168 updated readme and created an env.template file
  docs/README.md
  docs/env.template
  docs/exporting_keys.md
Labels: not reviewed
