Repository systers/sysbot, pull requests merged in 2018-07, with the labels that each got.

#88 Added travis config file.
  .coveragerc
  .gitignore
  .travis.yml
  code/auth_credentials.py
  code/github_functions.py
  code/main_server.py
  code/request_urls.py
  code/slack_functions.py
  requirements.txt
  setup.cfg
  tests/test_github_functions.py
  tests/test_slack_functions.py
Labels: under review

#90 Added unit tests for trying the environment variables. Work in progress.
  code/__init__.py
  code/github_functions.py
  tests/__init__.py
  tests/setup_data.py
  tests/test_github_functions.py
Labels: Work In Progress

#91 Added unit tests. Coverage 49%.
  .travis.yml
  code/github_functions.py
  code/slack_functions.py
  tests/setup_data.py
  tests/test_github_functions.py
  tests/test_slack_functions.py
Labels: under review

#95 Added feature to mention slack teams
  code/auth_credentials.py
  code/dictionaries.py
  code/main_server.py
  code/messages.py
  code/request_urls.py
  code/slack_functions.py
  tests/setup_data.py
Labels: under review

#99 Added design doc for answering questions
  .gitignore
  docs/answering_design.md
Labels: under review

#103 Answer with projects list
  .gitignore
  code/auth_credentials.py
  code/dictionaries.py
  code/main_server.py
  code/messages.py
  code/slack_functions.py
  setup.cfg
Labels: GSoC-18, under review

#110 Feature: Check if PR template has been followed
  code/github_functions.py
  code/main_server.py
  code/messages.py
Labels: Approved, GSoC-18

#113 Made changes for auto-deployment and fixed reply feature
  code/dictionaries.py
  code/github_functions.py
  deploy.sh
  main_server.py
Labels: GSoC-18, bug-fix, not reviewed

#122 Testing: Done 60 percent coverage
  code/main_server.py
  code/slack_functions.py
  tests/setup_data.py
  tests/test_main_server.py
  tests/test_slack_functions.py
Labels: GSoC-18, Testing, under review

#124 Fixes #120: Highlighting comands in README.md file
  docs/README.md
Labels: not reviewed

#125 tests: Tests added to cover 90% of code
  code/main_server.py
  code/messages.py
  code/slack_functions.py
  code/topic_extractor.py
  tests/setup_data.py
  tests/test_github_functions.py
  tests/test_main_server.py
  tests/test_slack_functions.py
Labels: GSoC-18, Testing, not reviewed

#131 chore: Collected, changed and curated event data
  .coveragerc
  setup.cfg
  simulate/data/github_data.json
  simulate/data/slack_data.json
Labels: not reviewed
